name: Build PvZ Toolkit

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC x86
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86

      - name: Download and extract FLTK
        shell: bash
        run: |
          curl -L -k -o fltk.zip https://github.com/fltk/fltk/releases/download/fltk-1.3.8/fltk-1.3.8-release-x86.zip
          powershell -command "Expand-Archive -Path fltk.zip -DestinationPath . -Force"
          mv fltk-1.3.8-release fltk

      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLTK_DIR="fltk/CMake" -S ..

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pvztoolkit-exe
          path: build/pvztoolkit.exe
          retention-days: 30

      - name: Upload Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: build/pvztoolkit.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
